"""empty message

Revision ID: a6918cbd76f9
Revises: 
Create Date: 2020-05-14 11:07:26.629220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6918cbd76f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_name', sa.String(length=64), nullable=True),
    sa.Column('country_code', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_country_code'), 'test', ['country_code'], unique=False)
    op.create_index(op.f('ix_test_country_name'), 'test', ['country_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_country_name'), table_name='test')
    op.drop_index(op.f('ix_test_country_code'), table_name='test')
    op.drop_table('test')
    # ### end Alembic commands ###
